import { StyleSheet } from "@react-pdf/renderer";

export const pdfStyles = StyleSheet.create({
  page: {
    padding: 20,
    fontFamily: "Roboto",
    fontSize: 8.2,
    backgroundColor: "#fff",
  },
  image: {
    width: 200,
    height: 150,
  },
  orgHeader: {
    fontSize: 10,
    fontWeight: "bold",
    alignSelf: "center",
    marginBottom: 1,
  },
  formTitle: {
    fontSize: 15,
    fontWeight: "bold",
    alignSelf: "center",
    marginBottom: 4,
  },
  sectionHeader: {
    fontSize: 9,
    fontWeight: "bold",
    marginTop: 4,
    marginBottom: 1,
    backgroundColor: "#f4f4f4",
    padding: 2,
    border: "1 solid #000",
    textAlign: "center",
  },
  box: {
    border: "1 solid #000",
    marginBottom: 1,
    padding: 3,
  },
  row: {
    flexDirection: "row",
    alignItems: "flex-end",
  },
  label: {
    fontWeight: "bold",
    fontSize: 8.1,
    marginRight: 3,
  },
  value: {
    flex: 1,
    borderBottom: "1 solid #888",
    fontSize: 8.2,
    paddingLeft: 1,
    paddingBottom: 1,
  },
  blockCheck: {
    border: "1 solid #000",
    width: 9,
    height: 9,
    marginRight: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  checkLabel: {
    fontSize: 8.2,
  },
  smallBt: {
    fontSize: 7,
    marginTop: 1,
  },
  uwagiHeader: {
    fontWeight: "bold",
    fontSize: 9,
    marginBottom: 1,
    marginTop: 2,
  },
  emptyBox: {
    border: "1 solid #888",
    minHeight: 35,
    padding: 2,
  },
  podpisy: {
    flexDirection: "row",
    marginTop: 8,
    justifyContent: "space-between",
  },
  podpis: {
    borderTop: "1 solid #000",
    width: 120,
    textAlign: "center",
    paddingTop: 1,
    fontSize: 8,
    marginTop: 40,
  },
  table: {
    border: "1 solid #000",
    marginBottom: 1,
  },
  tableHeaderRow: {
    flexDirection: "row",
    backgroundColor: "#f4f4f4",
    borderBottom: "1 solid #000",
  },
  tableHeaderCell: {
    flex: 2,
    padding: 3,
    fontSize: 7.5,
    fontWeight: "bold",
    textAlign: "center",
    borderRight: "1 solid #000",
  },
  tableHeaderCellSmall: {
    flex: 1,
    padding: 3,
    fontSize: 7.5,
    fontWeight: "bold",
    textAlign: "center",
    borderRight: "1 solid #000",
  },
  tableHeaderCellLast: {
    flex: 1.5,
    padding: 3,
    fontSize: 7.5,
    fontWeight: "bold",
    textAlign: "center",
  },
  tableDataRow: {
    flexDirection: "row",
    minHeight: 18,
    borderBottom: "1 solid #000",
  },
  tableDataRowLast: {
    flexDirection: "row",
    minHeight: 18,
  },
  tableDataCell: {
    flex: 1,
    padding: 2,
    fontSize: 7,
    borderRight: "1 solid #000",
    justifyContent: "center",
  },
  tableDataCellLast: {
    flex: 1.5,
    padding: 2,
    fontSize: 7,
    justifyContent: "center",
  },
});
